Temporary

diff --git a/.github/workflows/build-media.yml b/.github/workflows/build-media.yml
--- a/.github/workflows/build-media.yml
+++ b/.github/workflows/build-media.yml
@@ -229,145 +229,145 @@ jobs:
           notify_mattermost: ${{ inputs.notify_mattermost }}
 
 
-  start-aarch64-runner:
-    name: ${{ inputs.version_major != '8' && format('Runner for {0} {1} {2}', inputs.version_major, matrix.arch, matrix.image_type) || format('{0} aarch64 runner [EXCLUDED]', inputs.version_major) }}
-    runs-on: ubuntu-24.04
-    needs: [init-data]
-    strategy:
-      fail-fast: false
-      matrix:
-        # Set image types matrix based on boolean inputs.* with true value
-        image_type: ${{ fromJSON(format('["{0}", "{1}", "{2}", "{3}", "{4}"]', ( inputs.GNOME && 'GNOME' ), ( inputs.GNOME-Mini && 'GNOME-Mini' ), ( inputs.KDE && 'KDE' ), ( inputs.MATE && 'MATE' ), ( inputs.XFCE && 'XFCE' ) )) }}
-        version: ${{ fromJSON(format('["{0}"]', inputs.version_major)) }}
-        arch: [aarch64]
-        exclude:
-          - image_type: 'false'
-          - version: 8
-            arch: aarch64
-          # 10 and Kitten, GNOME and GNOME-Mini images are almost the same by size because of lack of some packages, like libreoffice group
-          - image_type: GNOME-Mini
-            version: 10
-          - image_type: GNOME-Mini
-            version: 10-kitten
-          # TODO: the excludes below should be removed when EPEL for 10 provides need packages
-          - version: 10-kitten
-            arch: aarch64
-            image_type: MATE
-          - version: 10-kitten
-            arch: aarch64
-            image_type: XFCE
-          - version: 10
-            arch: aarch64
-            image_type: MATE
-          - version: 10
-            arch: aarch64
-            image_type: XFCE
+  # start-aarch64-runner:
+  #   name: ${{ inputs.version_major != '8' && format('Runner for {0} {1} {2}', inputs.version_major, matrix.arch, matrix.image_type) || format('{0} aarch64 runner [EXCLUDED]', inputs.version_major) }}
+  #   runs-on: ubuntu-24.04
+  #   needs: [init-data]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # Set image types matrix based on boolean inputs.* with true value
+  #       image_type: ${{ fromJSON(format('["{0}", "{1}", "{2}", "{3}", "{4}"]', ( inputs.GNOME && 'GNOME' ), ( inputs.GNOME-Mini && 'GNOME-Mini' ), ( inputs.KDE && 'KDE' ), ( inputs.MATE && 'MATE' ), ( inputs.XFCE && 'XFCE' ) )) }}
+  #       version: ${{ fromJSON(format('["{0}"]', inputs.version_major)) }}
+  #       arch: [aarch64]
+  #       exclude:
+  #         - image_type: 'false'
+  #         - version: 8
+  #           arch: aarch64
+  #         # 10 and Kitten, GNOME and GNOME-Mini images are almost the same by size because of lack of some packages, like libreoffice group
+  #         - image_type: GNOME-Mini
+  #           version: 10
+  #         - image_type: GNOME-Mini
+  #           version: 10-kitten
+  #         # TODO: the excludes below should be removed when EPEL for 10 provides need packages
+  #         - version: 10-kitten
+  #           arch: aarch64
+  #           image_type: MATE
+  #         - version: 10-kitten
+  #           arch: aarch64
+  #           image_type: XFCE
+  #         - version: 10
+  #           arch: aarch64
+  #           image_type: MATE
+  #         - version: 10
+  #           arch: aarch64
+  #           image_type: XFCE
 
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4.0.2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+  #   steps:
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4.0.2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Get AlmaLinux ${{ inputs.version_major }} aarch64 AMI most recent ID
-        run: |
-          os_version="${{ inputs.version_major }}"
-          if [[ "${os_version}" == "10-kitten" ]]; then
-            os_version="Kitten 10"
-          fi
-          AMI_ID=$(aws ec2 describe-images --owners 764336703387 --query "Images | max_by(@, &CreationDate) | ImageId" --filters "Name=name,Values=AlmaLinux OS ${os_version}*aarch64" --region ${{ secrets.AWS_REGION }} --output text)
-          if [[ "${AMI_ID}" == "" || "${AMI_ID}" == "None" ]]; then
-            echo "[Error] Failed to get AMI ID for AlmaLinux ${os_version} aarch64."
-            exit 1
-          else
-            echo "[Debug] AMI ID: '${AMI_ID}'"
-          fi
-          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV
+  #     - name: Get AlmaLinux ${{ inputs.version_major }} aarch64 AMI most recent ID
+  #       run: |
+  #         os_version="${{ inputs.version_major }}"
+  #         if [[ "${os_version}" == "10-kitten" ]]; then
+  #           os_version="Kitten 10"
+  #         fi
+  #         AMI_ID=$(aws ec2 describe-images --owners 764336703387 --query "Images | max_by(@, &CreationDate) | ImageId" --filters "Name=name,Values=AlmaLinux OS ${os_version}*aarch64" --region ${{ secrets.AWS_REGION }} --output text)
+  #         if [[ "${AMI_ID}" == "" || "${AMI_ID}" == "None" ]]; then
+  #           echo "[Error] Failed to get AMI ID for AlmaLinux ${os_version} aarch64."
+  #           exit 1
+  #         else
+  #           echo "[Debug] AMI ID: '${AMI_ID}'"
+  #         fi
+  #         echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV
 
-      - name: Setup and start the runner
-        if: ${{ inputs.version_major != '8' }}
-        id: start-ec2-runner
-        uses: NextChapterSoftware/ec2-action-builder@v1.7
-        with:
-          github_token: ${{ secrets.GIT_HUB_TOKEN }}
-          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: ${{ secrets.AWS_REGION }}
-          ec2_ami_id: ${{ env.AMI_ID }}
-          ec2_subnet_id: ${{ secrets.EC2_SUBNET_ID}}
-          ec2_security_group_id: ${{ secrets.EC2_SECURITY_GROUP_ID }}
+  #     - name: Setup and start the runner
+  #       if: ${{ inputs.version_major != '8' }}
+  #       id: start-ec2-runner
+  #       uses: NextChapterSoftware/ec2-action-builder@v1.7
+  #       with:
+  #         github_token: ${{ secrets.GIT_HUB_TOKEN }}
+  #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws_region: ${{ secrets.AWS_REGION }}
+  #         ec2_ami_id: ${{ env.AMI_ID }}
+  #         ec2_subnet_id: ${{ secrets.EC2_SUBNET_ID}}
+  #         ec2_security_group_id: ${{ secrets.EC2_SECURITY_GROUP_ID }}
 
-          ec2_instance_type: t4g.medium       # 2 vCPU and 4 GiM Memory
-          ec2_root_disk_size_gb: "24"         # override default size which is too small for images
-          ec2_root_disk_ebs_class: "gp3"      # use faster and cheeper storage instead of default 'gp2'
-          ec2_instance_ttl: 60                # Optional (default is 60 minutes)
-          ec2_spot_instance_strategy: None    # Other options are: SpotOnly, BestEffort, MaxPerformance
-          ec2_instance_tags: >                # Required for IAM role resource permission scoping
-            [
-                {"Key": "Project", "Value": "GitHub Actions Self-hosted Runners"}
-            ]
+  #         ec2_instance_type: t4g.medium       # 2 vCPU and 4 GiM Memory
+  #         ec2_root_disk_size_gb: "24"         # override default size which is too small for images
+  #         ec2_root_disk_ebs_class: "gp3"      # use faster and cheeper storage instead of default 'gp2'
+  #         ec2_instance_ttl: 60                # Optional (default is 60 minutes)
+  #         ec2_spot_instance_strategy: None    # Other options are: SpotOnly, BestEffort, MaxPerformance
+  #         ec2_instance_tags: >                # Required for IAM role resource permission scoping
+  #           [
+  #               {"Key": "Project", "Value": "GitHub Actions Self-hosted Runners"}
+  #           ]
 
-  build-aarch64:
-    name: ${{ inputs.version_major != '8' && format('{0} {1} {2}', inputs.version_major, matrix.arch, matrix.image_type) || format('{0} aarch64 [EXCLUDED]', inputs.version_major) }}
-    runs-on: ${{ inputs.version_major != '8' && github.run_id || 'ubuntu-24.04' }}
-    if: ${{ always() && contains(join(needs.start-aarch64-runner.result, ','), 'success') }}
-    needs: [init-data, start-aarch64-runner]
-    strategy:
-      fail-fast: false
-      matrix:
-        # Set image types matrix based on boolean inputs.* with true value
-        image_type: ${{ fromJSON(format('["{0}", "{1}", "{2}", "{3}", "{4}"]', ( inputs.GNOME && 'GNOME' ), ( inputs.GNOME-Mini && 'GNOME-Mini' ), ( inputs.KDE && 'KDE' ), ( inputs.MATE && 'MATE' ), ( inputs.XFCE && 'XFCE' ) )) }}
-        version: ${{ fromJSON(format('["{0}"]', inputs.version_major)) }}
-        arch: [aarch64]
-        exclude:
-          - image_type: 'false'
-          - version: 8
-            arch: aarch64
-          # 10 and Kitten, GNOME and GNOME-Mini images are almost the same by size because of lack of some packages, like libreoffice group
-          - image_type: GNOME-Mini
-            version: 10
-          - image_type: GNOME-Mini
-            version: 10-kitten
-          # TODO: the excludes below should be removed when EPEL for 10 provides need packages
-          - version: 10-kitten
-            arch: aarch64
-            image_type: MATE
-          - version: 10-kitten
-            arch: aarch64
-            image_type: XFCE
-          - version: 10
-            arch: aarch64
-            image_type: MATE
-          - version: 10
-            arch: aarch64
-            image_type: XFCE
+  # build-aarch64:
+  #   name: ${{ inputs.version_major != '8' && format('{0} {1} {2}', inputs.version_major, matrix.arch, matrix.image_type) || format('{0} aarch64 [EXCLUDED]', inputs.version_major) }}
+  #   runs-on: ${{ inputs.version_major != '8' && github.run_id || 'ubuntu-24.04' }}
+  #   if: ${{ always() && contains(join(needs.start-aarch64-runner.result, ','), 'success') }}
+  #   needs: [init-data, start-aarch64-runner]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # Set image types matrix based on boolean inputs.* with true value
+  #       image_type: ${{ fromJSON(format('["{0}", "{1}", "{2}", "{3}", "{4}"]', ( inputs.GNOME && 'GNOME' ), ( inputs.GNOME-Mini && 'GNOME-Mini' ), ( inputs.KDE && 'KDE' ), ( inputs.MATE && 'MATE' ), ( inputs.XFCE && 'XFCE' ) )) }}
+  #       version: ${{ fromJSON(format('["{0}"]', inputs.version_major)) }}
+  #       arch: [aarch64]
+  #       exclude:
+  #         - image_type: 'false'
+  #         - version: 8
+  #           arch: aarch64
+  #         # 10 and Kitten, GNOME and GNOME-Mini images are almost the same by size because of lack of some packages, like libreoffice group
+  #         - image_type: GNOME-Mini
+  #           version: 10
+  #         - image_type: GNOME-Mini
+  #           version: 10-kitten
+  #         # TODO: the excludes below should be removed when EPEL for 10 provides need packages
+  #         - version: 10-kitten
+  #           arch: aarch64
+  #           image_type: MATE
+  #         - version: 10-kitten
+  #           arch: aarch64
+  #           image_type: XFCE
+  #         - version: 10
+  #           arch: aarch64
+  #           image_type: MATE
+  #         - version: 10
+  #           arch: aarch64
+  #           image_type: XFCE
 
-    env:
-      RUNNER: self-hosted
-      TIME_STAMP: ${{ needs.init-data.outputs.time_stamp }}
-      RESULT_DIR: /sig-livemedia
+  #   env:
+  #     RUNNER: self-hosted
+  #     TIME_STAMP: ${{ needs.init-data.outputs.time_stamp }}
+  #     RESULT_DIR: /sig-livemedia
 
-    steps:
-      - name: Checkout ${{ github.action_repository }}
-        if: inputs.version_major != '8'
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout ${{ github.action_repository }}
+  #       if: inputs.version_major != '8'
+  #       uses: actions/checkout@v4
 
-      - uses: ./.github/actions/shared-steps
-        name: ${{ matrix.version }} ${{ matrix.arch }} ${{ matrix.image_type }}
-        if: inputs.version_major != '8' && matrix.image_type != ''
-        with:
-          image_type: ${{ matrix.image_type }}
-          version_major: ${{ inputs.version_major }}
-          arch: ${{ matrix.arch }}
-          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
-          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
-          AWS_REGION: ${{ secrets.AWS_REGION }}
-          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
-          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
-          MATTERMOST_CHANNEL: ${{ vars.MATTERMOST_CHANNEL }}
-          iteration: ${{ inputs.iteration }}
-          store_as_artifact: ${{ inputs.store_as_artifact }}
-          upload_to_s3: ${{ inputs.upload_to_s3 }}
-          notify_mattermost: ${{ inputs.notify_mattermost }}
+  #     - uses: ./.github/actions/shared-steps
+  #       name: ${{ matrix.version }} ${{ matrix.arch }} ${{ matrix.image_type }}
+  #       if: inputs.version_major != '8' && matrix.image_type != ''
+  #       with:
+  #         image_type: ${{ matrix.image_type }}
+  #         version_major: ${{ inputs.version_major }}
+  #         arch: ${{ matrix.arch }}
+  #         S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
+  #         S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
+  #         AWS_REGION: ${{ secrets.AWS_REGION }}
+  #         AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
+  #         MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
+  #         MATTERMOST_CHANNEL: ${{ vars.MATTERMOST_CHANNEL }}
+  #         iteration: ${{ inputs.iteration }}
+  #         store_as_artifact: ${{ inputs.store_as_artifact }}
+  #         upload_to_s3: ${{ inputs.upload_to_s3 }}
+  #         notify_mattermost: ${{ inputs.notify_mattermost }}
